DESC PRODUCTO;
COMMIT;

INSERT INTO PRODUCTO(IDPRODUCTO, NOMBRE, PRECIO, STOCK) 
VALUES(1, 'TECLADO', 9.99, 10);

INSERT INTO PRODUCTO(IDPRODUCTO, NOMBRE, PRECIO, STOCK) 
VALUES(1, 'TECLADO', 9.99, 100);

UPDATE PRODUCTO 
SET PRECIO = 11
WHERE IDPRODUCTO = 1;

DELETE FROM PRODUCTO 
WHERE IDPRODUCTO = 1;


SELECT * FROM PRODUCTO;

UPDATE PRODUCTO
SET IDPRODUCTO = 22, NOMBRE = 'RATON EDITADO', PRECIO = 20, STOCK = 20
WHERE IDPRODUCTO = 2;

SELECT IDPRODUCTO, NOMBRE, PRECIO, STOCK
FROM PRODUCTO
WHERE IDPRODUCTO = 22;




SELECT IDPRODUCTO, NOMBRE, PRECIO, STOCK
FROM PRODUCTO;
