CREATE TABLE VEHICULO(
idVehiculo INT PRIMARY KEY,
fabricante NVARCHAR2(20) NOT NULL,
modelo NVARCHAR2(20) NOT NULL,
color NVARCHAR2(15) NOT NULL,
PRECIO NUMBER(8,2) NOT NULL
);

COMMIT;
DESC VEHICULO;
SELECT * FROM VEHICULO;

INSERT INTO VEHICULO(IDVEHICULO, FABRICANTE, MODELO, COLOR, PRECIO) 
VALUES(1, 'RENAULT', 'MEGAN', 'ROJO', 32000.99);

INSERT INTO VEHICULO(IDVEHICULO, FABRICANTE, MODELO, COLOR, PRECIO)
VALUES(2, 'RENAULT', 'CLIO', 'AZUL', 30000);
INSERT INTO VEHICULO(IDVEHICULO, FABRICANTE, MODELO, COLOR, PRECIO)
VALUES(3, 'OPEL', 'SIGMA', 'VERDE', 35000);
INSERT INTO VEHICULO(IDVEHICULO, FABRICANTE, MODELO, COLOR, PRECIO)
VALUES(4, 'RENAULT', 'CLIO', 'NEGRO', 32000);
INSERT INTO VEHICULO(IDVEHICULO, FABRICANTE, MODELO, COLOR, PRECIO)
VALUES(5, 'RENAULT', 'MEGAN', 'AMARILLO', 31000);
INSERT INTO VEHICULO(IDVEHICULO, FABRICANTE, MODELO, COLOR, PRECIO)
VALUES(6, 'OPEL', 'SIGMA', 'ROJO', 36000);
